/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UseNative */

#ifndef _Included_UseNative
#define _Included_UseNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     UseNative
 * Method:    cppfunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_UseNative_cppfunc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
